stages:
  - build
  - test
  - deploy
before_script:
  - export REMOTE_USER=ubuntu
  - export REMOTE_MACHINE_IP=XXX.XX.X.XX
  - export DEPLOYMENT_DIR=/opt/ib/voice-banking-middleware/`date +%F_%H.%M.%S`
  - export DEPLOYMENT_SOFT_LINK=/opt/ib/bean-mapper-middleware/latest
  - export JAVA_EXECUTABLE=/usr/lib/jvm/java-17-openjdk-amd64/bin/java

build-in-dev-build-agent-2(50):
  stage: build

  only:
    - branch-name

  tags:
    - build-agent-1

  script:
    - ls
    - ./gradlew clean build -x test
    - ls

test-in-dev-build-agent-2(50):
  stage: test

  only:
    - branch-name

  tags:
    - build-agent-1

  script:
    - ls
    - ./gradlew clean test

deploy-in-dev-bkb-api(223):
  stage: deploy

  only:
    - branch-name

  tags:
    - build-agent-1

  script:
    - ./gradlew clean build -x test
    - cd build/libs
    - ssh ${REMOTE_USER}@${REMOTE_MACHINE_IP} "mkdir -p ${DEPLOYMENT_DIR}"
    - scp *.jar ${REMOTE_USER}@${REMOTE_MACHINE_IP}:${DEPLOYMENT_DIR}
    - id=`echo $(ssh ${REMOTE_USER}@${REMOTE_MACHINE_IP} "ps aux | grep voice-banking-middleware | grep -v grep" | awk '{print $2}')`
    - echo $id
    - ssh ${REMOTE_USER}@${REMOTE_MACHINE_IP} "kill -9 $id || echo 0"
    - ssh ${REMOTE_USER}@${REMOTE_MACHINE_IP} "rm -rf ${DEPLOYMENT_SOFT_LINK}; ln -s ${DEPLOYMENT_DIR} ${DEPLOYMENT_SOFT_LINK}"
    - ssh ${REMOTE_USER}@${REMOTE_MACHINE_IP} "cd ${DEPLOYMENT_SOFT_LINK} ; nohup ${JAVA_EXECUTABLE} -jar bean-mapper-middleware-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &"

  after_script:
    - sleep 20
    - echo 'CICD Done '
